### ISSUE TITLE
mb-edit-set_work_attributes no longer functions

### ISSUE THREAD

**Issue by yindesu** [loujine/musicbrainz-scripts#93]
The URL include filter on https://github.com/loujine/musicbrainz-scripts/blob/master/mb-edit-set_work_attributes.user.js is too restrictive, but even expanding it, the userscript no longer functions as it originally did - neither the per-work dropdown lists nor the edit panel are drawn on https://musicbrainz.org/artist/53b106e7-0cc6-42cc-ac95-ed8d30a3a98e/works?filter.type_id=22&filter.name=&filter.role_type=

**Comment by mihawk90** [comment]
Same on [Olivier Derivière](https://musicbrainz.org/artist/885d2001-2d0d-4a80-8d8e-8ed49d270f1a)
What's odd is that it shows a select field on the first Work (["We are Family"](https://musicbrainz.org/work/3b1b1301-1618-4fd6-994c-26a792f894b4)), but nothing else:
![image](https://github.com/loujine/musicbrainz-scripts/assets/556162/cebd8477-990c-40ee-bb34-349a26750eb8)

The same is true for John Williams mentioned above:
![image](https://github.com/loujine/musicbrainz-scripts/assets/556162/47e461b4-55b5-4736-a3df-dd3f095cea4a)

**Comment by mihawk90** [comment]
Hm, ran across this again with [Ilan Eshkeri](https://musicbrainz.org/artist/d96b227e-87fb-4391-ac1a-8a2657ead68b).

Oddly in that case, the select field mentioned above does not show up:

![image](https://github.com/user-attachments/assets/ee2eb13f-8db0-485c-8c1e-db1d745069fd)

It still does on the 2 examples above.

The difference here being that the first row already has a Type, so it seems it's breaking on the first row overall. I first thought it was the first row without a type.

There is one error in the Dev Tools:
```
02:54:13.984 userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:878 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'textContent')
    at HTMLTableRowElement.<anonymous> (userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:878:32)
    at Function.each (jquery.js:384:23)
    at EVdnBjI.m.fn.init.each (jquery.js:136:17)
    at Object.<anonymous> (userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:871:7)
    at Pt (<anonymous>:10:89)
    at userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:1:89
    at window.__f__m2zl37d4.od (userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:1:368)
    at Pt (<anonymous>:10:89)
    at r.setMessageListener.r (<anonymous>:86:186)
    at <anonymous>:89:107
    at _ (<anonymous>:22:406)
(anonymous) @ userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:878
each @ jquery.js:384
each @ jquery.js:136
(anonymous) @ userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:871
Pt @ VM135:10
(anonymous) @ userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:1
window.__f__m2zl37d4.od @ userscript.html?name=MusicBrainz-edit%253A-Set-work-attributes-from-the-composer-Work-page.user.js&id=3a5d4ece-794e-4f17-87bd-4c804d93d953:1
Pt @ VM135:10
r.setMessageListener.r @ VM135:86
(anonymous) @ VM135:89
_ @ VM135:22
Show 2 more frames
Show less
```
